# Generated by Django 3.2.9 on 2021-12-03 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date closed'),
            preserve_default=False,
        ),
    ]
