# Generated by Django 3.2.9 on 2021-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211203_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
