# Generated by Django 3.2.9 on 2021-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_question_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed',
            field=models.NullBooleanField(default=False),
        ),
    ]
