# Generated by Django 3.2.9 on 2021-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_question_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
