# Generated by Django 3.2.9 on 2021-12-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_question_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='closed',
        ),
    ]
