# Generated by Django 3.2.9 on 2021-12-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_question_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(verbose_name='date closed'),
        ),
    ]
